# Generated by Django 3.0.2 on 2020-05-13 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='month',
            new_name='location',
        ),
    ]
