# Generated by Django 2.2.7 on 2020-02-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bills'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='ispaid',
            field=models.BooleanField(default=False),
        ),
    ]
