# Generated by Django 2.2.7 on 2020-04-27 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bills_ispaid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bills',
            new_name='Bill',
        ),
    ]
