# Generated by Django 2.2.7 on 2020-04-27 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200427_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='date_due',
        ),
    ]
